PACKAGE_NAME="uinput-tegra"
PACKAGE_VERSION="6.8.12-r39.2"

BUILT_MODULE_NAME[0]="uinput"
BUILT_MODULE_LOCATION[0]="drivers/input/misc"
DEST_MODULE_LOCATION[0]="/kernel/drivers/input/misc"

AUTOINSTALL="yes"
MAKE[0]="make KERNELRELEASE=${kernelver}"

BUILD_EXCLUSIVE_ARCH="aarch64"
BUILD_EXCLUSIVE_KERNEL="^6\\.8\\.12-[0-9]+-tegra$"
BUILD_EXCLUSIVE_CONFIG="CONFIG_INPUT !CONFIG_INPUT_UINPUT"
